### ISSUE TITLE
Use bookmarks for incremental backup

### ISSUE THREAD

**Issue by davidchisnall** [someone1/zfsbackup-go#8]
Recent versions of ZFS have a feature that allows storing the metadata changes, but not the data, for snapshots.  This is useful for creating backup checkpoints, where you want to know what has changed since the last backup, but don't want to record the old versions.  The typical workflow is:

* Initial backup:
  1. Create snapshot.
  2. Back up snapshot 
  3. Transform snapshot into bookmark
* Incremental backup:
  1. Create snapshot
  2. Back up the stream between the last bookmark and the current snapshot.
  3. Transform snapshot into bookmark
  4. [Optional] Delete old bookmark.

When you restore, you can either discard intermediate snapshots, or record them, but the local machine requires a negligible amount of space.

**Comment by someone1** [comment]
This should be possible without too much hassle I think, though I think since we match on snapshot names currently, we'd have to force bookmarks to be named after the snapshot they're made from to make this work (unfortunately I've only encountered identifiers such as GUIDs for snapshots on ZoL, not FreeBSD - not even sure if it's for the snapshot or the volume as I don't really use ZoL). From what little testing I've done with bookmarks so far, it doesn't seem there's any property on the bookmark that would point me to the snapshot it was made from.

The way I could see this working is forcing users to name bookmarks after the snapshots they're made from (e.g. `zfs bookmark tank/data@snap tank/data#snap`) and the code updated to treat the '@' and '#' characters for denoting <volume>@/#<snapshot/bookmark> equally.

If you have more experience with bookmarks, please let me know if you can think of a better way to implement. I'll be sure to do my homework properly prior to coding a solution, but any tips you may have would help!

Great feature request!

**Comment by davidchisnall** [comment]
Honestly, it had never occurred to me that a bookmark would have any name other than that of the snapshot that it was made from!  I'm using bookmarks to backup a hosted VM to my NAS: it takes a snapshot, backs up the difference from that snapshot to the last bookmark, then turns the snapshot into a bookmark.  On the receiving end, I have a lot more space so I just keep all of the previous snapshots around.

**Comment by davidchisnall** [comment]
It looks as if something that fixed this was committed, but I don't see anything documenting how you tell zfsbackup-go to use bookmarks.

**Comment by someone1** [comment]
#13 adds this but I got stuck trying to make it work with ZoL 0.6 - wanted to try and figure that out before merging but at this point I may just abandon support for ZoL 0.6 - no new release in almost 2 years and aside from LTS OS releases, 0.7 should be more prevalent.
